PROGRAM EJEMPLO_7_1
  IMPLICIT NONE
  ! Definición de variables
  INTEGER , PARAMETER :: NROW=5
  INTEGER , PARAMETER :: NCOL=6
  REAL , DIMENSION(1:NROW,1:NCOL) :: RESULT_EXAMS = 0.0
  REAL , DIMENSION(1:NROW)        :: MEDIA_ESTUD  = 0.0
  REAL , DIMENSION(1:NCOL)        :: MEDIA_ASIGN  = 0.0
  INTEGER :: R,C
  !
  ! Abrir fichero para lectura
  OPEN(UNIT=20,FILE='notas.dat',STATUS='OLD')
  !
  DO R=1,NROW
     READ(UNIT=20,FMT=100) RESULT_EXAMS(R,1:NCOL),MEDIA_ESTUD(R)
