       PROGRAM PROJEC
       REAL HGHTO, HGHT, VELOCO, VELOC, ACCEL, TIME

       ACCEL = -9.807
       PRINT *, 'ENTER THE INITIAL HEIGHT AND VELOCITY: '
       READ *, HGHTO, VELOCO
       PRINT *, 'ENTER TIME WHICH TO CALCULATE HEIGHT AND VELOCITY:'
       READ *, TIME
       HGHT =  0.5 * ACCEL * TIME ** 2 + VELOCO * TIME + HGHTO
       VELOC = ACCEL * TIME + VELOCO
       PRINT *, 'AT TIME ', TIME, 'THE VERTICAL VELOCITY IS ', VELOC
       PRINT *, 'AND THE HEIGHT IS ', HGHT
       END
